# Site settings
title: Hare and Edelweiss
tagline: "Bespoke Cushions"
url: "http://yourwebsite.com" # The base hostname & protocol for your site. Use it if you need absolute URL's
sass:
  style: compressed

# Collections
collections:
  projects:
    title: Projects
    output: true
  posts:
    title: Posts
    output: true

# Social
socialimg:
facebook: fbusername
github: ghusername
instagram: hareandedelweiss

# Contact
phone: "0000000" # This is my real number. You should text me.
email: "hello@me.com" # This is my real email address. Please don't email me.

# Use this for production
#sass:
#    style: :compressed

exclude: [.scss, README.md, node_modules, gruntfile.js, package.json]
