---
title: Hare and Edelweiss
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  projects:
    title: Projects
    output: true
  uploads:
    title: Uploads
    output: true
tagline: Bespoke Cushions
sass:
  style: compressed
socialimg: 
facebook: 
github: humont
instagram: hareandedelweiss
phone: 
email: 
exclude:
- ".scss"
- README.md
- node_modules
- gruntfile.js
- package.json
