---
title: Hare and Edelweiss
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  projects:
    title: Projects
    output: false
defaults:
  - scope:
      path: ""
      type: projects
    values:
      image-1:
      image-2:
      title:
      about:
  # - scope:
    #   path: ""
    #   type: posts
    # values:
    #   layout: post
    #   title:
    #   image:
    #   date:
    #   about:
    #   menu: "dark"
    #   color: "#fff2fa"

tagline: Bespoke Cushions

sass:
  style: compressed

socialimg:
facebook:
github: humont
instagram: hareandedelweiss
phone:
email:
exclude:
- ".scss"
- README.md
- node_modules
- gruntfile.js
- package.json
