---
title: Hare and Edelweiss
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  projects:
    title: Projects
    output: true
  uploads:
    title: Uploads
    output: true
tagline: Bespoke Cushions
sass:
  style: compressed
socialimg: 
facebook: fbusername
github: ghusername
instagram: hareandedelweiss
phone: '0000000'
email: hello@me.com
exclude:
- ".scss"
- README.md
- node_modules
- gruntfile.js
- package.json
