---
title: Hare and Edelweiss
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  projects:
    title: Projects
    output: false
  uploads:
    title: Uploads
    output: true
defaults:
- scope:
    path: ''
    type: projects
  values:
    image-1: 
    image-2: 
    title: 
    about: 
tagline: Bespoke Cushions
sass:
  style: compressed
socialimg: 
facebook: 
github: humont
instagram: hareandedelweiss
phone: 
email: 
exclude:
- ".scss"
- README.md
- node_modules
- gruntfile.js
- package.json
