backend:
  name: git-gateway
  branch: master

publish_mode: editorial_workflow

display_url: https://hareandeidelweiss.com

media_folder: "/assets/"

collections:
  - name: "projects"
    label: "Projects"
    folder: "_projects"
    create: true
    slug: "{{title}}"
    fields:
      - {label: "Layout", name: "layout", widget: "hidden", default: "project"}
      - {label: "Title", name: "title", widget: "string", required: true}
      - {label: "Image", name: "image", widget: "file",  required: true}
      - {label: "Body", name: "body", widget: "markdown", required: false}
  - label: "Pages"
    name: "pages"
    files:
      - label: "About"
        name: "about"
        file: "site/about.md"
        fields:
          - {label: Title, name: title, widget: string}
          - {label: Intro, name: intro, widget: markdown}
          - label: Team
            name: team
            widget: list
            fields:
              - {label: Name, name: name, widget: string}
              - {label: Position, name: position, widget: string}
              - {label: Photo, name: photo, widget: image}
      - label: "Contact"
        name: "contact"
        file: "site/contact.md"
        fields:
          - {label: Title, name: title, widget: string}
          - {label: Intro, name: intro, widget: markdown}
          - label: Locations
            name: locations
            widget: list
            fields:
              - {label: Name, name: name, widget: string}
              - {label: Address, name: address, widget: string}
